import type { Software, Category, NewsItem, Review } from './types';

export const categories: Category[] = [
  {
    id: 'security',
    name: 'Security',
    slug: 'security',
    icon: 'Shield',
    count: 1284,
    subcategories: [
      { name: 'Antivirus', count: 142 },
      { name: 'Firewall', count: 86 },
      { name: 'VPN', count: 214 },
      { name: 'Password Managers', count: 97 },
      { name: 'Encryption', count: 134 },
    ],
  },
  {
    id: 'multimedia',
    name: 'Multimedia',
    slug: 'multimedia',
    icon: 'Film',
    count: 2156,
    subcategories: [
      { name: 'Video Players', count: 312 },
      { name: 'Audio Editors', count: 287 },
      { name: 'Video Editors', count: 445 },
      { name: 'Image Viewers', count: 198 },
      { name: 'Codecs', count: 156 },
    ],
  },
  {
    id: 'system',
    name: 'System Utilities',
    slug: 'system',
    icon: 'Wrench',
    count: 1874,
    subcategories: [
      { name: 'Optimization', count: 234 },
      { name: 'Backup & Recovery', count: 189 },
      { name: 'Disk Management', count: 145 },
      { name: 'Drivers', count: 567 },
      { name: 'Monitoring', count: 123 },
    ],
  },
  {
    id: 'internet',
    name: 'Internet',
    slug: 'internet',
    icon: 'Globe',
    count: 1432,
    subcategories: [
      { name: 'Browsers', count: 89 },
      { name: 'Download Managers', count: 134 },
      { name: 'FTP Clients', count: 76 },
      { name: 'Messaging', count: 234 },
      { name: 'Email Clients', count: 156 },
    ],
  },
  {
    id: 'office',
    name: 'Office Tools',
    slug: 'office',
    icon: 'FileText',
    count: 987,
    subcategories: [
      { name: 'PDF Tools', count: 234 },
      { name: 'Word Processors', count: 89 },
      { name: 'Spreadsheets', count: 67 },
      { name: 'Note-taking', count: 145 },
      { name: 'Calendar', count: 78 },
    ],
  },
  {
    id: 'programming',
    name: 'Programming',
    slug: 'programming',
    icon: 'Code',
    count: 1123,
    subcategories: [
      { name: 'IDEs', count: 145 },
      { name: 'Text Editors', count: 234 },
      { name: 'Compilers', count: 89 },
      { name: 'Database Tools', count: 167 },
      { name: 'Version Control', count: 78 },
    ],
  },
  {
    id: 'games',
    name: 'Games',
    slug: 'games',
    icon: 'Gamepad2',
    count: 3451,
    subcategories: [
      { name: 'Action', count: 567 },
      { name: 'Puzzle', count: 423 },
      { name: 'Strategy', count: 345 },
      { name: 'RPG', count: 289 },
      { name: 'Simulation', count: 234 },
    ],
  },
  {
    id: 'drivers',
    name: 'Drivers',
    slug: 'drivers',
    icon: 'HardDrive',
    count: 2876,
    subcategories: [
      { name: 'Graphics', count: 234 },
      { name: 'Audio', count: 145 },
      { name: 'Network', count: 189 },
      { name: 'Printer', count: 312 },
      { name: 'Chipset', count: 167 },
    ],
  },
];

export const software: Software[] = [
  {
    id: 'vlc',
    name: 'VLC Media Player',
    slug: 'vlc-media-player',
    version: '3.0.21',
    developer: 'VideoLAN',
    description: 'Free, open-source, portable cross-platform media player and streaming media server.',
    longDescription: 'VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols. VLC is one of the most popular media players in the world, known for its ability to play virtually any video or audio format without requiring additional codecs.',
    category: 'multimedia',
    subcategory: 'Video Players',
    platforms: ['Windows', 'Mac', 'Linux', 'Android', 'iOS'],
    license: 'Open Source',
    fileSize: '42.3 MB',
    updatedAt: '2026-08-12',
    rating: 4.8,
    votes: 28456,
    downloads: '28.3M',
    iconColor: 'from-orange-500 to-orange-600',
    icon: 'Play',
    features: [
      'Plays virtually any video and audio format',
      'Hardware decoding on most platforms',
      'Supports 4K and 8K video playback',
      'Stream to network or transcode',
      'Subtitle synchronization and conversion',
      'Skinnable interface with customizable themes',
      'Extensions and plugins support',
      'No spyware, no ads, no user tracking',
    ],
    screenshots: [],
    changelog: [
      { version: '3.0.21', date: '2026-08-12', changes: ['Fixed HLS playback regression', 'Updated codec libraries', 'Improved HDR handling on macOS'] },
      { version: '3.0.20', date: '2026-06-03', changes: ['Added AV1 hardware decoding', 'Fixed subtitle positioning on HiDPI displays', 'Updated translations'] },
      { version: '3.0.19', date: '2026-03-15', changes: ['Security patches for MP4 demuxer', 'New DASH streaming improvements', 'Crash fixes on Windows 11'] },
    ],
    architectures: ['64-bit Installer', '32-bit Installer', 'Portable ZIP', 'macOS DMG', 'Linux Package'],
    techSpecs: [
      { label: 'Operating System', value: 'Windows 7/8/10/11, macOS 10.13+, Linux, Android 4.2+, iOS 11+' },
      { label: 'Language Support', value: '48 languages' },
      { label: 'Architecture', value: 'x86, x86_64, ARM, ARM64' },
      { label: 'SHA-256 Checksum', value: 'a3f5c8d2e1b9f4728e6c0a1d3b5e7f9c2d4a6b8e0f2c4d6a8b0e2f4d6c8a0b2' },
      { label: 'License', value: 'GNU GPL v2+' },
      { label: 'Developer', value: 'VideoLAN Organization' },
    ],
    verified: true,
    views: 8420000,
  },
  {
    id: '7zip',
    name: '7-Zip',
    slug: '7-zip',
    version: '23.01',
    developer: 'Igor Pavlov',
    description: 'Open-source file archiver with high compression ratio and AES-256 encryption.',
    longDescription: '7-Zip is a free and open-source file archiver, a utility used to place groups of files within compressed containers known as "archives". 7-Zip uses its own 7z archive format, but can read and write several other archive formats including ZIP, TAR, GZIP, BZIP2, and WIM.',
    category: 'system',
    subcategory: 'Optimization',
    platforms: ['Windows', 'Linux'],
    license: 'Open Source',
    fileSize: '1.5 MB',
    updatedAt: '2026-08-08',
    rating: 4.7,
    votes: 19234,
    downloads: '15.7M',
    iconColor: 'from-emerald-500 to-emerald-600',
    icon: 'Archive',
    features: [
      'High compression ratio in 7z format with LZMA/LZMA2',
      'AES-256 encryption for 7z and ZIP formats',
      'Self-extracting capability for 7z format',
      'Integration with Windows Shell',
      'Powerful File Manager with command line version',
      'Supports 79+ archive formats',
      'Localized for 87 languages',
    ],
    screenshots: [],
    changelog: [
      { version: '23.01', date: '2026-08-08', changes: ['Improved compression speed by 15%', 'Fixed path traversal vulnerability', 'Added support for Zstandard format'] },
      { version: '22.01', date: '2026-02-20', changes: ['Added ARM64 support for Windows', 'Improved multithreading for LZMA2', 'Bug fixes'] },
    ],
    architectures: ['64-bit Installer', '32-bit Installer', 'Portable', 'Linux Package'],
    techSpecs: [
      { label: 'Operating System', value: 'Windows 10/11, Linux' },
      { label: 'Language Support', value: '87 languages' },
      { label: 'Architecture', value: 'x86, x86_64, ARM64' },
      { label: 'SHA-256 Checksum', value: 'b2e8f1a4c7d9e3f6a0b2c4d6e8f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6' },
      { label: 'License', value: 'GNU LGPL' },
      { label: 'Developer', value: 'Igor Pavlov' },
    ],
    verified: true,
    views: 5200000,
  },
  {
    id: 'firefox',
    name: 'Mozilla Firefox',
    slug: 'mozilla-firefox',
    version: '128.0',
    developer: 'Mozilla Foundation',
    description: 'Fast, privacy-focused web browser with enhanced tracking protection and customization.',
    longDescription: 'Mozilla Firefox is a free and open-source web browser developed by the Mozilla Foundation. Firefox uses the Gecko layout engine to render web pages, which implements current and anticipated web standards. Firefox is known for its privacy features, customization options, and performance.',
    category: 'internet',
    subcategory: 'Browsers',
    platforms: ['Windows', 'Mac', 'Linux', 'Android', 'iOS'],
    license: 'Open Source',
    fileSize: '55.2 MB',
    updatedAt: '2026-08-15',
    rating: 4.6,
    votes: 45678,
    downloads: '52.1M',
    iconColor: 'from-blue-500 to-blue-600',
    icon: 'Globe',
    features: [
      'Enhanced Tracking Protection blocks third-party trackers',
      'Customizable interface with thousands of themes and extensions',
      'Built-in screenshot tool and PDF reader',
      'Picture-in-Picture video mode',
      'Containers for keeping tabs separate',
      'Sync across devices with Firefox Account',
      'Open source with no telemetry by default',
    ],
    screenshots: [],
    changelog: [
      { version: '128.0', date: '2026-08-15', changes: ['New privacy dashboard', 'Improved tab management', 'WebGPU support enabled by default'] },
      { version: '127.0', date: '2026-07-10', changes: ['Cookie isolation improvements', 'Faster startup time', 'Security fixes'] },
    ],
    architectures: ['64-bit Installer', '32-bit Installer', 'macOS DMG', 'Linux Package', 'Android APK'],
    techSpecs: [
      { label: 'Operating System', value: 'Windows 10/11, macOS 10.15+, Linux, Android 5.0+, iOS 13+' },
      { label: 'Language Support', value: '90+ languages' },
      { label: 'Architecture', value: 'x86, x86_64, ARM64' },
      { label: 'SHA-256 Checksum', value: 'c4a2b6d8e0f2a4c6b8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4' },
      { label: 'License', value: 'MPL 2.0' },
      { label: 'Developer', value: 'Mozilla Foundation' },
    ],
    verified: true,
    views: 12300000,
  },
  {
    id: 'gimp',
    name: 'GIMP',
    slug: 'gimp',
    version: '2.10.38',
    developer: 'GIMP Team',
    description: 'Free and open-source raster graphics editor for image retouching, composition and authoring.',
    longDescription: 'GIMP is a cross-platform image editor available for GNU/Linux, macOS, Windows, and more operating systems. Whether you are a graphic designer, photographer, illustrator, or scientist, GIMP provides you with sophisticated tools to get your job done.',
    category: 'multimedia',
    subcategory: 'Image Viewers',
    platforms: ['Windows', 'Mac', 'Linux'],
    license: 'Open Source',
    fileSize: '285 MB',
    updatedAt: '2026-07-28',
    rating: 4.5,
    votes: 15678,
    downloads: '12.4M',
    iconColor: 'from-slate-500 to-slate-600',
    icon: 'Image',
    features: [
      'Professional photo retouching tools',
      'Original artwork creation capabilities',
      'Extensible with plugins and scripts',
      'Supports many file formats including PSD',
      'Customizable interface with dockable panels',
      'Advanced scripting in Scheme and Python',
    ],
    screenshots: [],
    changelog: [
      { version: '2.10.38', date: '2026-07-28', changes: ['Improved color management', 'New filter previews', 'Performance improvements for large images'] },
      { version: '2.10.36', date: '2026-04-15', changes: ['Fixed layer group bugs', 'Updated GEGL engine', 'New brush dynamics'] },
    ],
    architectures: ['64-bit Installer', 'Portable', 'macOS DMG', 'Linux Package'],
    techSpecs: [
      { label: 'Operating System', value: 'Windows 8/10/11, macOS 10.14+, Linux' },
      { label: 'Language Support', value: '78 languages' },
      { label: 'Architecture', value: 'x86_64, ARM64' },
      { label: 'SHA-256 Checksum', value: 'd6e8f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2' },
      { label: 'License', value: 'GPL v3+' },
      { label: 'Developer', value: 'GIMP Team' },
    ],
    verified: true,
    views: 4100000,
  },
  {
    id: 'vscode',
    name: 'Visual Studio Code',
    slug: 'visual-studio-code',
    version: '1.92',
    developer: 'Microsoft',
    description: 'Free source code editor with debugging, syntax highlighting, and extensibility.',
    longDescription: 'Visual Studio Code is a free, source-code editor made by Microsoft for Windows, Linux and macOS. Features include support for debugging, syntax highlighting, intelligent code completion, snippets, code refactoring, and embedded Git.',
    category: 'programming',
    subcategory: 'IDEs',
    platforms: ['Windows', 'Mac', 'Linux'],
    license: 'Freeware',
    fileSize: '95 MB',
    updatedAt: '2026-08-10',
    rating: 4.9,
    votes: 67234,
    downloads: '38.9M',
    iconColor: 'from-blue-500 to-cyan-500',
    icon: 'Code',
    features: [
      'IntelliSense for smart completions',
      'Built-in Git version control',
      'Debugging support for Node.js and JavaScript',
      'Extensions marketplace with 40,000+ extensions',
      'Integrated terminal',
      'Multi-cursor editing',
      'Live Share collaborative editing',
    ],
    screenshots: [],
    changelog: [
      { version: '1.92', date: '2026-08-10', changes: ['New multi-root workspace improvements', 'Copilot integration enhancements', 'Performance fixes'] },
      { version: '1.91', date: '2026-07-05', changes: ['Improved language server protocol', 'New themes', 'Accessibility improvements'] },
    ],
    architectures: ['64-bit Installer', '32-bit Installer', 'macOS Universal', 'Linux .deb', 'Linux .rpm'],
    techSpecs: [
      { label: 'Operating System', value: 'Windows 10/11, macOS 10.15+, Linux' },
      { label: 'Language Support', value: '100+ languages' },
      { label: 'Architecture', value: 'x86_64, ARM64' },
      { label: 'SHA-256 Checksum', value: 'e8f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4' },
      { label: 'License', value: 'MIT License' },
      { label: 'Developer', value: 'Microsoft' },
    ],
    verified: true,
    views: 15600000,
  },
  {
    id: 'audacity',
    name: 'Audacity',
    slug: 'audacity',
    version: '3.6.0',
    developer: 'Muse Group',
    description: 'Free, open-source audio editor and recorder for multi-track editing and effects.',
    longDescription: 'Audacity is a free and open-source digital audio editor and recording application software. Audacity is available for Windows, macOS, and Linux operating systems. It is one of the most popular audio editing tools, used by podcasters, musicians, and content creators worldwide.',
    category: 'multimedia',
    subcategory: 'Audio Editors',
    platforms: ['Windows', 'Mac', 'Linux'],
    license: 'Open Source',
    fileSize: '38.7 MB',
    updatedAt: '2026-08-05',
    rating: 4.6,
    votes: 21456,
    downloads: '18.2M',
    iconColor: 'from-yellow-500 to-orange-500',
    icon: 'AudioLines',
    features: [
      'Multi-track audio editing',
      'Real-time effects preview',
      'Noise reduction and removal',
      'Support for VST plugins',
      'Recording from microphone and line input',
      'Export to MP3, WAV, OGG, and FLAC',
    ],
    screenshots: [],
    changelog: [
      { version: '3.6.0', date: '2026-08-05', changes: ['New real-time effects system', 'Improved noise reduction algorithm', 'MIDI support improvements'] },
      { version: '3.5.2', date: '2026-05-12', changes: ['Bug fixes for macOS', 'New keyboard shortcuts', 'Stability improvements'] },
    ],
    architectures: ['64-bit Installer', '32-bit Installer', 'macOS DMG', 'Linux Package'],
    techSpecs: [
      { label: 'Operating System', value: 'Windows 10/11, macOS 10.14+, Linux' },
      { label: 'Language Support', value: '35 languages' },
      { label: 'Architecture', value: 'x86_64, ARM64' },
      { label: 'SHA-256 Checksum', value: 'f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4c6' },
      { label: 'License', value: 'GPL v2+' },
      { label: 'Developer', value: 'Muse Group' },
    ],
    verified: true,
    views: 6300000,
  },
  {
    id: 'libreoffice',
    name: 'LibreOffice',
    slug: 'libreoffice',
    version: '7.6.5',
    developer: 'The Document Foundation',
    description: 'Free and open-source office suite with word processing, spreadsheets, and presentations.',
    longDescription: 'LibreOffice is a free and powerful office suite, and a successor to OpenOffice. It includes a word processor (Writer), a spreadsheet (Calc), a presentation application (Impress), a drawing application (Draw), a formula editor (Math), and a database management application (Base).',
    category: 'office',
    subcategory: 'Word Processors',
    platforms: ['Windows', 'Mac', 'Linux'],
    license: 'Open Source',
    fileSize: '340 MB',
    updatedAt: '2026-07-20',
    rating: 4.4,
    votes: 18234,
    downloads: '22.1M',
    iconColor: 'from-green-500 to-teal-500',
    icon: 'FileText',
    features: [
      'Full-featured word processor with Writer',
      'Spreadsheet application with Calc',
      'Presentation tool with Impress',
      'Database management with Base',
      'Vector graphics editor with Draw',
      'Formula editor with Math',
      'Microsoft Office file format compatibility',
    ],
    screenshots: [],
    changelog: [
      { version: '7.6.5', date: '2026-07-20', changes: ['Improved DOCX compatibility', 'New chart types in Calc', 'Performance improvements'] },
      { version: '7.6.3', date: '2026-04-08', changes: ['Security fixes', 'New templates', 'Translation updates'] },
    ],
    architectures: ['64-bit Installer', '32-bit Installer', 'macOS DMG', 'Linux Package'],
    techSpecs: [
      { label: 'Operating System', value: 'Windows 7/8/10/11, macOS 10.14+, Linux' },
      { label: 'Language Support', value: '115 languages' },
      { label: 'Architecture', value: 'x86, x86_64, ARM64' },
      { label: 'SHA-256 Checksum', value: 'a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8' },
      { label: 'License', value: 'MPL 2.0' },
      { label: 'Developer', value: 'The Document Foundation' },
    ],
    verified: true,
    views: 7800000,
  },
  {
    id: 'obs',
    name: 'OBS Studio',
    slug: 'obs-studio',
    version: '30.2.0',
    developer: 'OBS Project',
    description: 'Free open-source software for video recording and live streaming with scene composition.',
    longDescription: 'OBS Studio is a free and open-source software suite for recording and live streaming. It provides real-time video and audio capturing and mixing, scene composition, and encoding for various streaming platforms like Twitch, YouTube, and Facebook Live.',
    category: 'multimedia',
    subcategory: 'Video Editors',
    platforms: ['Windows', 'Mac', 'Linux'],
    license: 'Open Source',
    fileSize: '120 MB',
    updatedAt: '2026-08-14',
    rating: 4.8,
    votes: 32145,
    downloads: '16.8M',
    iconColor: 'from-gray-600 to-gray-700',
    icon: 'Video',
    features: [
      'Multi-source scene composition',
      'Real-time streaming to Twitch, YouTube, and more',
      'Custom transitions and filters',
      'Audio mixer with per-source filters',
      'Plugin support for extended functionality',
      'Replay buffer for capturing highlights',
      'Studio Mode for preview before going live',
    ],
    screenshots: [],
    changelog: [
      { version: '30.2.0', date: '2026-08-14', changes: ['New replay buffer UI', 'Improved NVENC encoder support', 'macOS screen capture fixes'] },
      { version: '30.1.0', date: '2026-05-22', changes: ['Added WebSocket 5 support', 'New audio visualizer filter', 'Performance improvements'] },
    ],
    architectures: ['64-bit Installer', 'macOS DMG', 'Linux Package'],
    techSpecs: [
      { label: 'Operating System', value: 'Windows 10/11, macOS 10.15+, Linux' },
      { label: 'Language Support', value: '50+ languages' },
      { label: 'Architecture', value: 'x86_64, ARM64' },
      { label: 'SHA-256 Checksum', value: 'b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0' },
      { label: 'License', value: 'GPL v2+' },
      { label: 'Developer', value: 'OBS Project' },
    ],
    verified: true,
    views: 9200000,
  },
  {
    id: 'bitwarden',
    name: 'Bitwarden',
    slug: 'bitwarden',
    version: '2026.8.0',
    developer: 'Bitwarden, Inc.',
    description: 'Open-source password manager with end-to-end encryption and cross-platform sync.',
    longDescription: 'Bitwarden is a free and open-source password management service that stores sensitive information like website credentials in an encrypted vault. The platform offers a variety of client applications including a web interface, desktop apps, browser extensions, and mobile apps.',
    category: 'security',
    subcategory: 'Password Managers',
    platforms: ['Windows', 'Mac', 'Linux', 'Android', 'iOS'],
    license: 'Open Source',
    fileSize: '78 MB',
    updatedAt: '2026-08-11',
    rating: 4.7,
    votes: 28901,
    downloads: '9.4M',
    iconColor: 'from-blue-600 to-indigo-600',
    icon: 'Shield',
    features: [
      'End-to-end AES-256 bit encryption',
      'Cross-platform sync across all devices',
      'Password generator and strength tester',
      'Secure sharing with organizations',
      'Two-factor authentication support',
      'Self-host option available',
      'Bitwarden Send for encrypted file sharing',
    ],
    screenshots: [],
    changelog: [
      { version: '2026.8.0', date: '2026-08-11', changes: ['New passkey support', 'Improved autofill on Android', 'Security enhancements'] },
      { version: '2026.6.0', date: '2026-06-15', changes: ['Added SSH key management', 'New desktop UI', 'Performance fixes'] },
    ],
    architectures: ['64-bit Installer', 'macOS DMG', 'Linux Package', 'Android APK', 'iOS App Store'],
    techSpecs: [
      { label: 'Operating System', value: 'Windows 10/11, macOS 10.14+, Linux, Android 8.0+, iOS 14+' },
      { label: 'Language Support', value: '60+ languages' },
      { label: 'Architecture', value: 'x86_64, ARM64' },
      { label: 'SHA-256 Checksum', value: 'c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f2' },
      { label: 'License', value: 'GPL v3+' },
      { label: 'Developer', value: 'Bitwarden, Inc.' },
    ],
    verified: true,
    views: 4500000,
  },
  {
    id: 'handbrake',
    name: 'HandBrake',
    slug: 'handbrake',
    version: '1.8.2',
    developer: 'HandBrake Team',
    description: 'Open-source video transcoder for converting video to modern, widely supported codecs.',
    longDescription: 'HandBrake is a free and open-source transcoder for digital video files. It was originally developed in 2003 by Eric Petit to rip DVDs, and now supports most common multimedia files and any DVD or Blu-ray sources that do not contain copy protection.',
    category: 'multimedia',
    subcategory: 'Video Editors',
    platforms: ['Windows', 'Mac', 'Linux'],
    license: 'Open Source',
    fileSize: '25.4 MB',
    updatedAt: '2026-07-30',
    rating: 4.5,
    votes: 12345,
    downloads: '8.1M',
    iconColor: 'from-red-500 to-orange-500',
    icon: 'Disc',
    features: [
      'Convert video from nearly any format',
      'Built-in device presets for fast conversion',
      'Batch scanning and encoding',
      'Support for H.264, H.265, and AV1',
      'Subtitle support including VobSub',
      'Video filtering: deinterlacing, denoise, crop',
      'Audio pass-through and multi-track audio',
    ],
    screenshots: [],
    changelog: [
      { version: '1.8.2', date: '2026-07-30', changes: ['AV1 encoding improvements', 'New Apple Silicon optimizations', 'Bug fixes'] },
      { version: '1.8.0', date: '2026-04-20', changes: ['Added 10-bit encoding support', 'New preset system', 'Performance improvements'] },
    ],
    architectures: ['64-bit Installer', 'macOS DMG', 'Linux Package'],
    techSpecs: [
      { label: 'Operating System', value: 'Windows 10/11, macOS 10.14+, Linux' },
      { label: 'Language Support', value: '40+ languages' },
      { label: 'Architecture', value: 'x86_64, ARM64' },
      { label: 'SHA-256 Checksum', value: 'd8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f2a4' },
      { label: 'License', value: 'GPL v2+' },
      { label: 'Developer', value: 'HandBrake Team' },
    ],
    verified: true,
    views: 3800000,
  },
  {
    id: 'notepadpp',
    name: 'Notepad++',
    slug: 'notepad-plus-plus',
    version: '8.6.9',
    developer: 'Don Ho',
    description: 'Free source code editor and Notepad replacement supporting several programming languages.',
    longDescription: 'Notepad++ is a free text editor and source code editor for use with Microsoft Windows. It supports tabbed editing, which allows working with multiple open files in a single window. The name comes from the C increment operator, reflecting the software as a successor to Notepad.',
    category: 'programming',
    subcategory: 'Text Editors',
    platforms: ['Windows'],
    license: 'Open Source',
    fileSize: '4.2 MB',
    updatedAt: '2026-08-02',
    rating: 4.7,
    votes: 38456,
    downloads: '31.2M',
    iconColor: 'from-green-500 to-green-600',
    icon: 'FileEdit',
    features: [
      'Syntax highlighting for 80+ programming languages',
      'Multi-document tabbed interface',
      'Split screen editing',
      'Macro recording and playback',
      'Powerful search with regex support',
      'Plugin system with 200+ plugins',
      'Auto-completion for functions and words',
    ],
    screenshots: [],
    changelog: [
      { version: '8.6.9', date: '2026-08-02', changes: ['Fixed crash on large files', 'New dark mode improvements', 'Plugin manager updates'] },
      { version: '8.6.7', date: '2026-05-18', changes: ['Improved performance on large files', 'New language support', 'Security patches'] },
    ],
    architectures: ['64-bit Installer', '32-bit Installer', 'Portable'],
    techSpecs: [
      { label: 'Operating System', value: 'Windows 7/8/10/11' },
      { label: 'Language Support', value: '90+ languages' },
      { label: 'Architecture', value: 'x86, x86_64, ARM64' },
      { label: 'SHA-256 Checksum', value: 'e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f2a4' },
      { label: 'License', value: 'GPL v2+' },
      { label: 'Developer', value: 'Don Ho' },
    ],
    verified: true,
    views: 11200000,
  },
  {
    id: 'ccleaner',
    name: 'CCleaner',
    slug: 'ccleaner',
    version: '6.22',
    developer: 'Piriform',
    description: 'System optimization and privacy tool that removes unused files and cleans browsing history.',
    longDescription: 'CCleaner is a utility program used to clean potentially unwanted files and invalid Windows Registry entries from a computer. It is one of the most popular system optimization tools, helping users free up disk space and maintain privacy by clearing browsing data.',
    category: 'system',
    subcategory: 'Optimization',
    platforms: ['Windows', 'Mac'],
    license: 'Freeware',
    fileSize: '30 MB',
    updatedAt: '2026-08-09',
    rating: 4.2,
    votes: 25678,
    downloads: '45.6M',
    iconColor: 'from-cyan-500 to-blue-500',
    icon: 'Recycle',
    features: [
      'Cleans unused files and cache',
      'Registry cleaner and optimizer',
      'Browser history and cookie cleaner',
      'Uninstall manager for applications',
      'Startup program manager',
      'Duplicate file finder',
      'Drive wiper for secure deletion',
    ],
    screenshots: [],
    changelog: [
      { version: '6.22', date: '2026-08-09', changes: ['Improved Edge browser cleaning', 'New Software Updater feature', 'Performance fixes'] },
      { version: '6.20', date: '2026-05-04', changes: ['Updated cleaning rules for new apps', 'UI improvements', 'Bug fixes'] },
    ],
    architectures: ['64-bit Installer', '32-bit Installer', 'Portable', 'macOS DMG'],
    techSpecs: [
      { label: 'Operating System', value: 'Windows 7/8/10/11, macOS 10.12+' },
      { label: 'Language Support', value: '55 languages' },
      { label: 'Architecture', value: 'x86, x86_64' },
      { label: 'SHA-256 Checksum', value: 'f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f2a4b6' },
      { label: 'License', value: 'Freemium' },
      { label: 'Developer', value: 'Piriform Software Ltd' },
    ],
    verified: true,
    views: 13400000,
  },
];

export const newsItems: NewsItem[] = [
  {
    id: '1',
    title: 'VLC Media Player 3.0.21 Released with HDR Improvements',
    excerpt: 'The latest update brings better HDR handling on macOS and fixes HLS playback issues.',
    category: 'Multimedia',
    date: '2026-08-12',
    image: '',
  },
  {
    id: '2',
    title: 'Firefox 128 Adds WebGPU Support and Privacy Dashboard',
    excerpt: 'Mozilla pushes the web forward with WebGPU enabled by default and a new privacy overview.',
    category: 'Internet',
    date: '2026-08-15',
    image: '',
  },
  {
    id: '3',
    title: 'OBS Studio 30.2 Brings Replay Buffer Overhaul',
    excerpt: 'New replay buffer UI and improved NVENC encoder support for streamers.',
    category: 'Multimedia',
    date: '2026-08-14',
    image: '',
  },
  {
    id: '4',
    title: 'Bitwarden Introduces Passkey Management',
    excerpt: 'The open-source password manager now supports passkeys across all platforms.',
    category: 'Security',
    date: '2026-08-11',
    image: '',
  },
  {
    id: '5',
    title: 'Visual Studio Code 1.92 Enhances Copilot Integration',
    excerpt: 'Microsoft updates VS Code with deeper AI assistant integration and performance fixes.',
    category: 'Programming',
    date: '2026-08-10',
    image: '',
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    softwareId: 'vlc',
    author: 'Michael R.',
    rating: 5,
    date: '2026-08-10',
    title: 'The best media player, period.',
    body: 'VLC has been my go-to media player for over a decade. It plays everything I throw at it without needing any extra codecs. The interface is simple but powerful, and the fact that it is open source and ad-free makes it unbeatable.',
  },
  {
    id: 'r2',
    softwareId: 'vlc',
    author: 'Sarah K.',
    rating: 4,
    date: '2026-07-28',
    title: 'Great player, UI could use an update',
    body: 'VLC plays every format imaginable and I love it for that. The only reason I am not giving it 5 stars is that the interface feels a bit dated compared to some modern alternatives. Still, functionality-wise it cannot be beaten.',
  },
  {
    id: 'r3',
    softwareId: 'vlc',
    author: 'David L.',
    rating: 5,
    date: '2026-07-15',
    title: 'Indispensable tool',
    body: 'I use VLC daily for both video playback and as a streaming server. The network streaming capabilities are incredibly powerful and well-documented. Highly recommended for any media needs.',
  },
];

export function getSoftwareBySlug(slug: string): Software | undefined {
  return software.find((s) => s.slug === slug);
}

export function getSoftwareByCategory(categoryId: string): Software[] {
  return software.filter((s) => s.category === categoryId);
}

export function getRelatedSoftware(sw: Software, limit = 4): Software[] {
  return software
    .filter((s) => s.category === sw.category && s.id !== sw.id)
    .slice(0, limit);
}

export function getTopDownloads(limit = 10): Software[] {
  const downloadsValue = (d: string) => {
    const num = parseFloat(d);
    if (d.includes('M')) return num * 1000000;
    if (d.includes('K')) return num * 1000;
    return num;
  };
  return [...software].sort((a, b) => downloadsValue(b.downloads) - downloadsValue(a.downloads)).slice(0, limit);
}

export function getReviewsForSoftware(softwareId: string): Review[] {
  return reviews.filter((r) => r.softwareId === softwareId);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}
