/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  images: {
    unoptimized: true,
  },
  eslint: {
    // Build ke waqt ESLint errors ignore karne ke liye:
    ignoreDuringBuilds: true,
  },
  typescript: {
    // Build ke waqt Typescript errors ignore karne ke liye:
    ignoreBuildErrors: true,
  },
};

module.exports = nextConfig;
